export const ERRORS_DESCRIPTION = {
  // Auction
  PNE: 'Auction::bid: this pool does not exist',
  AF: 'Auction::bid: auction finished',
  NBG: 'Auction::bid: next bid should be greater than previous',
  COY: 'Auction::bid: bid already exists',
  ANF: 'Auction::claimDebtOwnership: auction not finished',
  AC: 'Auction::claimDebtOwnership: already claimed',
  NAE: 'Auction::resolveAuction: No auction exists',
  NID: 'Auction::_startAuction: pool is not in default',
  NWB: 'Auction::_startAuction: only whitelisted bidder can start auction',
  LMB: 'Auction::_startAuciton: amount less tham min bid',
  NBD: 'Auction::increaseBid: no bid exists, nothing to increase',
  OSB: 'Auction::increaseBid: only second place winner can withdraw bid',
  NBE: 'Auction: Should wait for next bid',
  ESF: 'Auction: End should be in future',
  NPM: 'Auction:: pool manager not allowed',
  TNP: 'Auction::resolveAuctionWithoutGoverment: timeout not passed yet',
  ALL: 'Auction: auction time extends max time limit',
  IVL: 'Auction: Invalid value',
  LBA: 'Auction: low bid amount',
  // FlashGovernor
  PNA: 'FlashGovernor::propose: this proposer is not allowed',
  PWS: 'FlashGovernor: proposal is in wrong state',
  HWA: 'FlashGovernor::vote: voter has voted already',
  APE: 'FlashGovernor::execute: only allowed proposer can execute',
  VPZ: 'FlashGovernor::setVotingPeriod: voting period should be greater than zero',
  // MembershipStaking
  NES: 'MembershipStaking::unstake: not enough stake',
  NYD: 'MembershipStaking::getPriorVotes: not yet determined',
  OF: 'MembershipStaking: only factory can call this function',
  // PoolFactory
  MHI: 'PoolFactory: manager should have info',
  PNS: 'PoolFactory::createPool: proposal not succeeded',
  NPP: 'PoolFactory::cancelPool: no proposed pool with this manager',
  GTO: 'PoolFactory: argument should not be greater than 1',
  SNP: 'PoolFactory::closePool: sender is not pool',
  CNA: 'PoolFactory: this currency is not allowed',
  AHP: 'PoolFactory: this manager already has pool',
  AHI: 'PoolFactory::_setManager: manager already has info',
  CEI: 'PoolFactory::_setManager: can not set empty info',
  SAU: 'PoolFactory::_setManager: manager symbol already used',
  NPA: 'PoolFactory::withdrawReward: not a pool address',
  PAI: 'Pools already initialized',
  SNA: 'PoolFactory::sweep CPOOL not allowed',
  FNI: 'Factory not initialized',
  TZ: 'PoolFactory::_createPool: treasury is zero',
  RFZ: 'PoolFactory::_createPool: reserve factor is zero',
  IFZ: 'PoolFactory::_createPool: insurance factor is zero',
  WUZ: 'PoolFactory::_createPool: warning utilization is zero',
  PUZ: 'PoolFactory::_createPool: provisional default utilization is zero',
  WGZ: 'PoolFactory::_createPool: warning grace period is zero',
  PAZ: 'PoolFactory::_createPool: period to start auction is zero',
  WLP: 'PoolFactory::_createPool: warning utilization should be less than provisional default utilization',
  CZ: 'PoolFactory::setCurrency: currency is zero address',
  MHZ: 'PoolFactory::setManager: manager hash is zero',
  // PoolMaster
  RCT: 'Pool restricted country',
  CAM: 'Pool country attribute is missing',
  HAS: 'Pool high AML score',
  ALM: 'Pool KYC attributes length mismatch',
  CBZ: 'Pool::borrow: can not borrow zero',
  NEL: 'Pool::borrow: not enough liquidity',
  MTB: 'Pool::repay: impossible to repay more than borrowed',
  SCC: 'Pool::close: sender can not close pool',
  PIA: 'Pool is not active',
  PIF: 'Pool is not fully active',
  OM: 'Only manager can call this function',
  OOD: 'Only owner of debt can call this function',
  OA: 'Only auction can call this function',
  NEC: 'Not enough currency',
  PIC: 'Pool::_close: pool is closed',
  CDC: "Pool::allowWithdrawalAfterNoAuction: can't distribute insurance and close",
  BNZ: 'Pool::repay: borrows non zero',
  OGM: 'Pool::changeCapacity: Only governor or manager can change maximum capacity',
  CPM: "Pool::provide: can't provide more than maximum capacity",
  // AavePoolMaster
  OU: 'Already upgraded',
  // Interest rate model
  HMR: 'Higher than max rate',
  // Global
  ZAM: 'Amount is zero',
  AIZ: 'Address is zero',
  OG: 'Only governor can call this function',
  LTZ: 'Less than zero',
}

export const ERRORS = {
  AUCTION: {
    POOL_NOT_EXIST: 'PNE',
    AUCTION_FINISHED: 'AF',
    NEXT_BID_GREATER: 'NBG',
    CANT_BID_AFTER_YOURSELF: 'COY',
    AUCTION_NOT_FINISHED: 'ANF',
    NO_AUCTION_EXISTS: 'NAE',
    ALREADY_CLAIMED: 'AC',
    NOT_IN_DEFAULT: 'NID',
    NOT_WHITELISTED_BIDDER: 'NWB',
    LESS_MIN_BID: 'LMB',
    NO_BID_MADE: 'NBD',
    ONLY_SECOND_PLACE_BIDDER: 'OSB',
    NEXT_BID_TOO_EARLY: 'NBE',
    END_SHOULD_BE_IN_FUTURE: 'ESF',
    POOL_MANAGER_NOT_ALLOWED: 'NPM',
    TIMEOUT_NOT_PASSED: 'TNP',
    AMOUNT_IS_ZER0: 'AZ',
    AUCTION_LENGTH_LIMIT: 'ALL',
    INVALID_VALUE: 'IVL',
    LOW_BID_AMOUNT: 'LBA',
  },
  FLASH_GOVERNOR: {
    PROPOSER_NOT_ALLOWED: 'PNA',
    PROPOSAL_WRONG_STATE: 'PWS',
    HAS_VOTED_ALREADY: 'HWA',
    ALLOWED_PROPOSER_EXECUTE: 'APE',
    VOTING_PERIOD_ZERO: 'VPZ',
  },
  STAKING: {
    NOT_ENOUGH_STAKE: 'NES',
    NOT_YET_DETERMINED: 'NYD',
    ONLY_FACTORY: 'OF',
  },
  POOL_FACTORY: {
    MANAGER_HAVE_INFO: 'MHI',
    NO_PROPOSED_POOL: 'NPP',
    GREATER_THAN_ONE: 'GTO',
    SENDER_NOT_POOL: 'SNP',
    CURRENCY_NOT_ALLOWED: 'CNA',
    ALREADY_HAS_POOL: 'AHP',
    ALREADY_HAS_INFO: 'AHI',
    CANT_EMPTY_INFO: 'CEI',
    SYMBOL_ALREADY_USED: 'SAU',
    NOT_POOL_ADDRESS: 'NPA',
    SWEEP_NOT_ALLOWED: 'SNA',
    FACTORY_NOT_INITIALIZED: 'FNI',
    TREASURY_IS_ZERO: 'TZ',
    RESERVE_FACTOR_IS_ZERO: 'RFZ',
    INSURANCE_FACTOR_IS_ZERO: 'IFZ',
    WARNING_UTILIZATION_IS_ZERO: 'WUZ',
    PROVISIONAL_DEFAULT_UTILIZATION_IS_ZERO: 'PUZ',
    WARNING_GRACE_PERIOD_IS_ZERO: 'WGZ',
    PERIOD_TO_START_AUCTION_IS_ZERO: 'PAZ',
    WARNING_ALWAYS_LESS_THAN_PROVISIONAL: 'WLP',
    CURRENCY_IS_ZERO: 'CZ',
    MANAGER_HASH_IS_ZERO: 'MHZ',
  },
  POOL_MASTER: {
    RESTRICTED_COUNTRY: 'RCT',
    COUNTRY_ATTRIBUTE_MISSING: 'CAM',
    HIGH_AML_SCORE: 'HAS',
    ATTRIBUTES_LENGTH_MISMATCH: 'ALM',
    CANT_BORROW_ZERO: 'CBZ',
    NOT_ENOUGH_LIQUIDITY: 'NEL',
    MORE_THAN_BORROWED: 'MTB',
    SENDER_CANT_CLOSE: 'SCC',
    POOL_ISNT_ACTIVE: 'PIA',
    ONLY_MANAGER: 'OM',
    ONLY_OWNER_OF_DEBT: 'OOD',
    ONLY_AUCTION: 'OA',
    NOT_ENOUGH_CURRENCY: 'NEC',
    CANT_DISTRIBUTE_AND_CLOSE: 'CDC',
    BORROWS_NON_ZERO: 'BNZ',
    ONLY_GOVERNOR_OR_MANAGER: 'OGM',
    CANT_PROVIDE_MORE_THAN_CAPACITY: 'CPM',
  },
  AAVE_POOL_MASTER: {
    ALREADY_UPGRADED: 'OU',
  },
  UPGRADE_CONTROLLER: {
    LENGTH_MISMATCH: 'LM',
    INVALID_SIGNATURE: 'IS',
  },
  GLOBAL: {
    AMOUNT_IS_ZERO: 'AZ',
    ADDRESS_IS_ZERO: 'AIZ',
    ONLY_GOVERNOR: 'OG',
    LESS_THAN_ZERO: 'LTZ',
  },
}
